defmodule ElixirApp.Repo.Migrations.AddOfferFavoriteMetric do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ash_offers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :amount, :decimal, null: false
      add :status, :text, default: "pending"
      add :message, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :property_id,
          references(:ash_properties,
            column: :id,
            name: "ash_offers_property_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :buyer_id,
          references(:users,
            column: :id,
            name: "ash_offers_buyer_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end

    create table(:ash_metric_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event_type, :text, null: false
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "ash_metric_events_user_id_fkey",
            type: :bigint,
            prefix: "public"
          )

      add :property_id,
          references(:ash_properties,
            column: :id,
            name: "ash_metric_events_property_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:ash_favorites, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :property_id,
          references(:ash_properties,
            column: :id,
            name: "ash_favorites_property_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :user_id,
          references(:users,
            column: :id,
            name: "ash_favorites_user_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end

    create unique_index(:ash_favorites, [:user_id, :property_id],
             name: "ash_favorites_unique_user_property_index"
           )
  end

  def down do
    drop constraint(:ash_favorites, "ash_favorites_property_id_fkey")

    drop constraint(:ash_favorites, "ash_favorites_user_id_fkey")

    drop_if_exists unique_index(:ash_favorites, [:user_id, :property_id],
                     name: "ash_favorites_unique_user_property_index"
                   )

    drop table(:ash_favorites)

    drop constraint(:ash_metric_events, "ash_metric_events_user_id_fkey")

    drop constraint(:ash_metric_events, "ash_metric_events_property_id_fkey")

    drop table(:ash_metric_events)

    drop constraint(:ash_offers, "ash_offers_property_id_fkey")

    drop constraint(:ash_offers, "ash_offers_buyer_id_fkey")

    drop table(:ash_offers)

  end
end
