defmodule ElixirApp.Repo.Migrations.AddRelationships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # users table is managed by Ecto — skip creation, just add FK constraint
    alter table(:ash_properties) do
      modify :owner_id,
             references(:users,
               column: :id,
               name: "ash_properties_owner_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    create index(:ash_properties, [:owner_id])
  end

  def down do
    drop_if_exists index(:ash_properties, [:owner_id])

    drop constraint(:ash_properties, "ash_properties_owner_id_fkey")

    alter table(:ash_properties) do
      modify :owner_id, :bigint
    end
  end
end
