defmodule ElixirApp.Repo.Migrations.InitialAshSetup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ash_properties, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :location, :text, null: false
      add :price, :decimal, null: false
      add :bedrooms, :bigint
      add :bathrooms, :bigint
      add :area, :float
      add :type, :text, default: "house"
      add :status, :text, default: "available"
      add :image_path, :text
      add :owner_id, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:ash_properties)
  end
end
